CREATE TABLE {schemaname}.{tablename} (
    CREATED_AT TIMESTAMP,
    DELIVERY_ID INT,
    DAY_OF_WEEK VARCHAR(65535),
    HOUR_OF_DAY VARCHAR(65535),
    DAYPART VARCHAR(65535),
    STORE_STARTING_POINT_ID DOUBLE PRECISION,
    SUBMARKET_ID DOUBLE PRECISION,
    WINDOW_ID DOUBLE PRECISION,
    hh_temperature DOUBLE PRECISION, 
    hh_apparent_temperature DOUBLE PRECISION,
    hh_pressure DOUBLE PRECISION, 
    hh_humidity DOUBLE PRECISION,
    hh_visibility DOUBLE PRECISION, 
    hh_wind_speed DOUBLE PRECISION,
    hh_cloud_cover DOUBLE PRECISION, 
    hh_dewpoint DOUBLE PRECISION,
    hh_precip_intensity DOUBLE PRECISION,
    hh_precip_probability DOUBLE PRECISION,
    hh_hourly_weather_summary VARCHAR(65535), 
    hh_icon VARCHAR(65535),
    pred_demand DOUBLE PRECISION, 
    actual_demand DOUBLE PRECISION,
    under_predicted_demand DOUBLE PRECISION,
    pw_hourly_avg_flf DOUBLE PRECISION, 
    pw_hourly_avg_is_flf_above_ideal DOUBLE PRECISION,
    pw_hourly_avg_is_flf_above_max DOUBLE PRECISION,
    pw_hourly_avg_dasher_pay_other DOUBLE PRECISION,
    IS_FLF_ABOVE_IDEAL BOOLEAN
);
